name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: ./.github/actions/install-deps
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --spec "cypress/e2e/specs/**/*.cy.js"